version: "3.5"

services:
  ms-vuelos:
    image: gabrielchavezr/ms-vuelos:v1
    ports:
      - "8182:80"
      - "4434:443"
    environment:
      mysql:cn: "server=database-mysql;database=db_vuelos;user=root;password=Vuelos123"
      #ConnectionStrings:mysql: "server=database-mysql;port=3307;database=AeronaveDb;user=root;password=Vuelos123"
    depends_on:
      - database-mysql
  database-mysql:
    image: mysql:8.0.26
    container_name: database-mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=Vuelos123
    ports:
    - 3307:3306
    - 33061:33060
    